# Site
name: "FrontierZero's Blog"
title: "FrontierZero"
description: "Technical and non-technical posts concerning cloud and SaaS security"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
mainwebsite: 'https://www.frontierzero.io'
google_analytics: 'G-HKSE2SJE67'
#disqus: ''
mailchimp-list: 'https://frontierzero.us18.list-manage.com/subscribe/post?u=56bb243d7dbab9593b4869365&amp;id=7b7262cd7e'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  morsy:
    name: Mohamed Morsy
    display_name: Mohamed Morsy
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: morsy@frontierzero.io
    web: https://www.frontierzero.io/
    #twitter: https://twitter.com/wowthemesnet
    linkedin: https://linkedin.com/in/morsyy
    description: "Co Founder"
  samir:
    name: Mahmoud Samir
    display_name: Mahmoud Samir
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: samir@frontierzero.io
    web: https://www.frontierzero.io/
    linkedin: https://www.linkedin.com/in/mahmoud-samir-37245b257/
    description: "Account Executive"
  amr:
    name: Amr Shams 
    display_name: Amr Shams
    gravatar: 
    email: amr@frontierzero.io
    web: https://www.linkedin.com/in/amr-m-shams/
    linkedin: https://www.linkedin.com/in/amr-m-shams/
    description: "Cybersecurity Analyst"
  oskars:
    name: Oskars Vientiess
    display_name: Oskars Vientiess
    gravatar: 
    email: oskars@frontierzero.io
    web: https://www.linkedin.com/in/oskars-vientiess/
    linkedin: https://www.linkedin.com/in/oskars-vientiess/
    description: "Marketing Manager"    
    


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-toc

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
